export interface Problem {
  id: number
  title: string
  slug: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  category: string
  leetcodeUrl: string
  isBlind75: true
}

export const BLIND75_CATEGORIES = [
  'Array',
  'Two Pointers',
  'Sliding Window',
  'String',
  'Hash Table',
  'Math',
  'Linked List',
  'Stack',
  'Binary Search',
  'Divide and Conquer',
  'Trees',
  'Heaps',
  'Graphs',
  'Dynamic Programming',
  'Backtracking',
  'Intervals',
  'Design',
  'Bit Manipulation',
]

export const BLIND75: Problem[] = [
  { id: 1, title: 'Two Sum', slug: 'two-sum', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/two-sum', isBlind75: true },
  { id: 2, title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-and-sell-stock', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock', isBlind75: true },
  { id: 3, title: 'Contains Duplicate', slug: 'contains-duplicate', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate', isBlind75: true },
  { id: 4, title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self', isBlind75: true },
  { id: 5, title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Easy', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray', isBlind75: true },
  { id: 6, title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray', isBlind75: true },
  { id: 7, title: 'Find Minimum in Rotated Sorted Array', slug: 'find-minimum-in-rotated-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array', isBlind75: true },
  { id: 8, title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array', isBlind75: true },
  { id: 9, title: 'Valid Parentheses', slug: 'valid-parentheses', difficulty: 'Easy', category: 'Stack', leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses', isBlind75: true },
  { id: 10, title: 'Merge Two Sorted Lists', slug: 'merge-two-sorted-lists', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists', isBlind75: true },
  { id: 11, title: 'Reverse Linked List', slug: 'reverse-linked-list', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list', isBlind75: true },
  { id: 12, title: 'Linked List Cycle', slug: 'linked-list-cycle', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle', isBlind75: true },
  { id: 13, title: 'Remove Nth Node From End of List', slug: 'remove-nth-node-from-end-of-list', difficulty: 'Medium', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list', isBlind75: true },
  { id: 14, title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/valid-anagram', isBlind75: true },
  { id: 15, title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/group-anagrams', isBlind75: true },
  { id: 16, title: 'Top K Frequent Elements', slug: 'top-k-frequent-elements', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements', isBlind75: true },
  { id: 17, title: 'Kth Largest Element in an Array', slug: 'kth-largest-element-in-an-array', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array', isBlind75: true },
  { id: 18, title: 'Sort Colors', slug: 'sort-colors', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/sort-colors', isBlind75: true },
  { id: 19, title: 'Product of Array Except Self (duplicate placeholder)', slug: 'product-of-array-except-self', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self', isBlind75: true },
  { id: 20, title: 'Insert Interval', slug: 'insert-interval', difficulty: 'Medium', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/insert-interval', isBlind75: true },
  { id: 21, title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/merge-intervals', isBlind75: true },
  { id: 22, title: 'Meeting Rooms', slug: 'meeting-rooms', difficulty: 'Easy', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms', isBlind75: true },
  { id: 23, title: 'Meeting Rooms II', slug: 'meeting-rooms-ii', difficulty: 'Medium', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-ii', isBlind75: true },
  { id: 24, title: 'Binary Tree Inorder Traversal', slug: 'binary-tree-inorder-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal', isBlind75: true },
  { id: 25, title: 'Binary Tree Level Order Traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal', isBlind75: true },
  { id: 26, title: 'Validate Binary Search Tree', slug: 'validate-binary-search-tree', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree', isBlind75: true },
  { id: 27, title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree', isBlind75: true },
  { id: 28, title: 'Populate Next Right Pointers', slug: 'populating-next-right-pointers-in-each-node', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node', isBlind75: true },
  { id: 29, title: 'Lowest Common Ancestor of a Binary Tree', slug: 'lowest-common-ancestor-of-a-binary-tree', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree', isBlind75: true },
  { id: 30, title: 'Search a 2D Matrix', slug: 'search-a-2d-matrix', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix', isBlind75: true },
  { id: 31, title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/number-of-islands', isBlind75: true },
  { id: 32, title: 'Course Schedule', slug: 'course-schedule', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/course-schedule', isBlind75: true },
  { id: 33, title: 'Clone Graph', slug: 'clone-graph', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/clone-graph', isBlind75: true },
  { id: 34, title: 'Graph Valid Tree', slug: 'graph-valid-tree', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/graph-valid-tree', isBlind75: true },
  { id: 35, title: 'Minimum Spanning Tree (concept)', slug: 'minimum-spanning-tree', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problemset/all/', isBlind75: true },
  { id: 36, title: 'Course Schedule II', slug: 'course-schedule-ii', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii', isBlind75: true },
  { id: 37, title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree', isBlind75: true },
  { id: 38, title: 'Word Search', slug: 'word-search', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/word-search', isBlind75: true },
  { id: 39, title: 'Combination Sum', slug: 'combination-sum', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/combination-sum', isBlind75: true },
  { id: 40, title: 'Subsets', slug: 'subsets', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/subsets', isBlind75: true },
  { id: 41, title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard', category: 'Sliding Window', leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring', isBlind75: true },
  { id: 42, title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium', category: 'Sliding Window', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters', isBlind75: true },
  { id: 43, title: 'Longest Palindromic Substring', slug: 'longest-palindromic-substring', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring', isBlind75: true },
  { id: 44, title: '3Sum', slug: '3sum', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/3sum', isBlind75: true },
  { id: 45, title: '3Sum Closest', slug: '3sum-closest', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/3sum-closest', isBlind75: true },
  { id: 46, title: 'Trapping Rain Water', slug: 'trapping-rain-water', difficulty: 'Hard', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water', isBlind75: true },
  { id: 47, title: 'Container With Most Water', slug: 'container-with-most-water', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water', isBlind75: true },
  { id: 48, title: 'Evaluate Reverse Polish Notation', slug: 'evaluate-reverse-polish-notation', difficulty: 'Medium', category: 'Stack', leetcodeUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation', isBlind75: true },
  { id: 49, title: 'Binary Tree Zigzag Level Order Traversal', slug: 'binary-tree-zigzag-level-order-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal', isBlind75: true },
  { id: 50, title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/binary-search', isBlind75: true },
  { id: 51, title: 'Search Insert Position', slug: 'search-insert-position', difficulty: 'Easy', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-insert-position', isBlind75: true },
  { id: 52, title: 'Find Peak Element', slug: 'find-peak-element', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/find-peak-element', isBlind75: true },
  { id: 53, title: 'Lowest Common Ancestor of a Binary Search Tree', slug: 'lowest-common-ancestor-of-a-binary-search-tree', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree', isBlind75: true },
  { id: 54, title: 'Product of Array (placeholder)', slug: 'product-of-array', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/product-of-array', isBlind75: true },
  { id: 55, title: 'Word Ladder', slug: 'word-ladder', difficulty: 'Hard', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/word-ladder', isBlind75: true },
  { id: 56, title: 'LRU Cache', slug: 'lru-cache', difficulty: 'Medium', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/lru-cache', isBlind75: true },
  { id: 57, title: 'Min Stack', slug: 'min-stack', difficulty: 'Easy', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/min-stack', isBlind75: true },
  { id: 58, title: 'Design Twitter', slug: 'design-twitter', difficulty: 'Medium', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/design-twitter', isBlind75: true },
  { id: 59, title: 'Number of Connected Components in an Undirected Graph', slug: 'number-of-connected-components-in-an-undirected-graph', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph', isBlind75: true },
  { id: 60, title: 'Satisfiability of Equality Equations', slug: 'satisfiability-of-equality-equations', difficulty: 'Medium', category: 'Union-Find', leetcodeUrl: 'https://leetcode.com/problems/satisfiability-of-equality-equations', isBlind75: true },
  { id: 61, title: 'Number of Islands II', slug: 'number-of-islands-ii', difficulty: 'Hard', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/number-of-islands-ii', isBlind75: true },
  { id: 62, title: 'House Robber', slug: 'house-robber', difficulty: 'Easy', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/house-robber', isBlind75: true },
  { id: 63, title: 'House Robber II', slug: 'house-robber-ii', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/house-robber-ii', isBlind75: true },
  { id: 64, title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence', isBlind75: true },
  { id: 65, title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/coin-change', isBlind75: true },
  { id: 66, title: 'Word Break', slug: 'word-break', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/word-break', isBlind75: true },
  { id: 67, title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs', isBlind75: true },
  { id: 68, title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum', isBlind75: true },
  { id: 69, title: 'Sum Root to Leaf Numbers', slug: 'sum-root-to-leaf-numbers', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/sum-root-to-leaf-numbers', isBlind75: true },
  { id: 70, title: 'Path Sum', slug: 'path-sum', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/path-sum', isBlind75: true },
  { id: 71, title: 'Palindrome Linked List', slug: 'palindrome-linked-list', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/palindrome-linked-list', isBlind75: true },
  { id: 72, title: 'Intersection of Two Linked Lists', slug: 'intersection-of-two-linked-lists', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/intersection-of-two-linked-lists', isBlind75: true },
  { id: 73, title: 'Copy List with Random Pointer', slug: 'copy-list-with-random-pointer', difficulty: 'Medium', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/copy-list-with-random-pointer', isBlind75: true },
  { id: 74, title: 'Maximum Frequency Stack', slug: 'maximum-frequency-stack', difficulty: 'Hard', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/maximum-frequency-stack', isBlind75: true },
  { id: 75, title: 'Median of Two Sorted Arrays', slug: 'median-of-two-sorted-arrays', difficulty: 'Hard', category: 'Divide and Conquer', leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays', isBlind75: true },
]

export default BLIND75
