import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().default("LeetCode Progress Analyzer"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  MONGODB_URI: z.string().min(1).default("mongodb://127.0.0.1:27017/leetcode-progress-analyzer"),
  MONGODB_DB: z.string().min(1).default("leetcode_progress_analyzer"),
  REDIS_URL: z.string().min(1).default("redis://127.0.0.1:6379"),
  LEETCODE_GRAPHQL_URL: z.string().url().default("https://leetcode.com/graphql"),
  GITHUB_GRAPHQL_URL: z.string().url().default("https://api.github.com/graphql"),
  GITHUB_TOKEN: z.string().optional().default(""),
  GITHUB_CLIENT_ID: z.string().optional().default(""),
  GITHUB_CLIENT_SECRET: z.string().optional().default(""),
  GOOGLE_CLIENT_ID: z.string().optional().default(""),
  GOOGLE_CLIENT_SECRET: z.string().optional().default(""),
  TELEGRAM_BOT_TOKEN: z.string().optional().default(""),
  TELEGRAM_CHAT_ID: z.string().optional().default(""),
  TELEGRAM_API_BASE_URL: z.string().url().default("https://api.telegram.org"),
  GROQ_API_KEY: z.string().optional().default(""),
  GROQ_MODEL: z.string().min(1).default("openai/gpt-oss-20b"),
  NEXTAUTH_SECRET: z.string().optional().default(""),
  NEXTAUTH_URL: z.string().url().optional().default("http://localhost:3000"),
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_DB: process.env.MONGODB_DB,
  REDIS_URL: process.env.REDIS_URL,
  LEETCODE_GRAPHQL_URL: process.env.LEETCODE_GRAPHQL_URL,
  GITHUB_GRAPHQL_URL: process.env.GITHUB_GRAPHQL_URL,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
  TELEGRAM_API_BASE_URL: process.env.TELEGRAM_API_BASE_URL,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  GROQ_MODEL: process.env.GROQ_MODEL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
});
