export interface NCProblem {
  id: number
  title: string
  slug: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  category: string
  leetcodeUrl: string
}

export const NEETCODE150: NCProblem[] = [
  { id: 1, title: 'Two Sum', slug: 'two-sum', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/two-sum' },
  { id: 2, title: 'Add Two Numbers', slug: 'add-two-numbers', difficulty: 'Medium', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/add-two-numbers' },
  { id: 3, title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium', category: 'Sliding Window', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters' },
  { id: 4, title: 'Median of Two Sorted Arrays', slug: 'median-of-two-sorted-arrays', difficulty: 'Hard', category: 'Divide and Conquer', leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays' },
  { id: 5, title: 'Longest Palindromic Substring', slug: 'longest-palindromic-substring', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring' },
  { id: 6, title: 'ZigZag Conversion', slug: 'zigzag-conversion', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/zigzag-conversion' },
  { id: 7, title: 'Reverse Integer', slug: 'reverse-integer', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/reverse-integer' },
  { id: 8, title: 'String to Integer (atoi)', slug: 'string-to-integer-atoi', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/string-to-integer-atoi' },
  { id: 9, title: 'Palindrome Number', slug: 'palindrome-number', difficulty: 'Easy', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/palindrome-number' },
  { id: 10, title: 'Regular Expression Matching', slug: 'regular-expression-matching', difficulty: 'Hard', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/regular-expression-matching' },
  { id: 11, title: 'Container With Most Water', slug: 'container-with-most-water', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water' },
  { id: 12, title: 'Integer to Roman', slug: 'integer-to-roman', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/integer-to-roman' },
  { id: 13, title: 'Roman to Integer', slug: 'roman-to-integer', difficulty: 'Easy', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/roman-to-integer' },
  { id: 14, title: 'Longest Common Prefix', slug: 'longest-common-prefix', difficulty: 'Easy', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix' },
  { id: 15, title: '3Sum', slug: '3sum', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/3sum' },
  { id: 16, title: '3Sum Closest', slug: '3sum-closest', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/3sum-closest' },
  { id: 17, title: 'Letter Combinations of a Phone Number', slug: 'letter-combinations-of-a-phone-number', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number' },
  { id: 18, title: '4Sum', slug: '4sum', difficulty: 'Medium', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/4sum' },
  { id: 19, title: 'Remove Nth Node From End of List', slug: 'remove-nth-node-from-end-of-list', difficulty: 'Medium', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list' },
  { id: 20, title: 'Valid Parentheses', slug: 'valid-parentheses', difficulty: 'Easy', category: 'Stack', leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses' },
  { id: 21, title: 'Merge Two Sorted Lists', slug: 'merge-two-sorted-lists', difficulty: 'Easy', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists' },
  { id: 22, title: 'Generate Parentheses', slug: 'generate-parentheses', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/generate-parentheses' },
  { id: 23, title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists' },
  { id: 24, title: 'Swap Nodes in Pairs', slug: 'swap-nodes-in-pairs', difficulty: 'Medium', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/swap-nodes-in-pairs' },
  { id: 25, title: 'Reverse Nodes in k-Group', slug: 'reverse-nodes-in-k-group', difficulty: 'Hard', category: 'Linked List', leetcodeUrl: 'https://leetcode.com/problems/reverse-nodes-in-k-group' },
  { id: 26, title: 'Remove Duplicates from Sorted Array', slug: 'remove-duplicates-from-sorted-array', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array' },
  { id: 27, title: 'Remove Element', slug: 'remove-element', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/remove-element' },
  { id: 28, title: 'Implement strStr()', slug: 'implement-strstr', difficulty: 'Easy', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/implement-strstr' },
  { id: 29, title: 'Divide Two Integers', slug: 'divide-two-integers', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/divide-two-integers' },
  { id: 30, title: 'Next Permutation', slug: 'next-permutation', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/next-permutation' },
  { id: 31, title: 'Longest Valid Parentheses', slug: 'longest-valid-parentheses', difficulty: 'Hard', category: 'Stack', leetcodeUrl: 'https://leetcode.com/problems/longest-valid-parentheses' },
  { id: 32, title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array' },
  { id: 33, title: 'Find First and Last Position of Element in Sorted Array', slug: 'find-first-and-last-position-of-element-in-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array' },
  { id: 34, title: 'Search Insert Position', slug: 'search-insert-position', difficulty: 'Easy', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-insert-position' },
  { id: 35, title: 'Search a 2D Matrix', slug: 'search-a-2d-matrix', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix' },
  { id: 36, title: 'Valid Sudoku', slug: 'valid-sudoku', difficulty: 'Medium', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku' },
  { id: 37, title: 'Sudoku Solver', slug: 'sudoku-solver', difficulty: 'Hard', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/sudoku-solver' },
  { id: 38, title: 'Count and Say', slug: 'count-and-say', difficulty: 'Easy', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/count-and-say' },
  { id: 39, title: 'Combination Sum', slug: 'combination-sum', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/combination-sum' },
  { id: 40, title: 'Combination Sum II', slug: 'combination-sum-ii', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/combination-sum-ii' },
  { id: 41, title: 'First Missing Positive', slug: 'first-missing-positive', difficulty: 'Hard', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/first-missing-positive' },
  { id: 42, title: 'Trapping Rain Water', slug: 'trapping-rain-water', difficulty: 'Hard', category: 'Two Pointers', leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water' },
  { id: 43, title: 'Multiply Strings', slug: 'multiply-strings', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/multiply-strings' },
  { id: 44, title: 'Wildcard Matching', slug: 'wildcard-matching', difficulty: 'Hard', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/wildcard-matching' },
  { id: 45, title: 'Jump Game', slug: 'jump-game', difficulty: 'Medium', category: 'Greedy', leetcodeUrl: 'https://leetcode.com/problems/jump-game' },
  { id: 46, title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/merge-intervals' },
  { id: 47, title: 'Insert Interval', slug: 'insert-interval', difficulty: 'Medium', category: 'Intervals', leetcodeUrl: 'https://leetcode.com/problems/insert-interval' },
  { id: 48, title: 'Length of Last Word', slug: 'length-of-last-word', difficulty: 'Easy', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/length-of-last-word' },
  { id: 49, title: 'Spiral Matrix', slug: 'spiral-matrix', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/spiral-matrix' },
  { id: 50, title: 'Jump Game II', slug: 'jump-game-ii', difficulty: 'Hard', category: 'Greedy', leetcodeUrl: 'https://leetcode.com/problems/jump-game-ii' },
  { id: 51, title: 'Permutations', slug: 'permutations', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/permutations' },
  { id: 52, title: 'Rotate Image', slug: 'rotate-image', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/rotate-image' },
  { id: 53, title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/group-anagrams' },
  { id: 54, title: 'Pow(x, n)', slug: 'powx-n', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/powx-n' },
  { id: 55, title: 'N-Queens', slug: 'n-queens', difficulty: 'Hard', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/n-queens' },
  { id: 56, title: 'N-Queens II', slug: 'n-queens-ii', difficulty: 'Hard', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/n-queens-ii' },
  { id: 57, title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard', category: 'Sliding Window', leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring' },
  { id: 58, title: 'Subarray Sum Equals K', slug: 'subarray-sum-equals-k', difficulty: 'Medium', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k' },
  { id: 59, title: 'Palindrome Partitioning', slug: 'palindrome-partitioning', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning' },
  { id: 60, title: 'Word Search', slug: 'word-search', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/word-search' },
  { id: 61, title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/word-search-ii' },
  { id: 62, title: 'Kth Largest Element in an Array', slug: 'kth-largest-element-in-an-array', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array' },
  { id: 63, title: 'Top K Frequent Elements', slug: 'top-k-frequent-elements', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements' },
  { id: 64, title: 'K Closest Points to Origin', slug: 'k-closest-points-to-origin', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/k-closest-points-to-origin' },
  { id: 65, title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists' },
  { id: 66, title: 'Binary Tree Inorder Traversal', slug: 'binary-tree-inorder-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal' },
  { id: 67, title: 'Binary Tree Preorder Traversal', slug: 'binary-tree-preorder-traversal', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-preorder-traversal' },
  { id: 68, title: 'Binary Tree Postorder Traversal', slug: 'binary-tree-postorder-traversal', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-postorder-traversal' },
  { id: 69, title: 'Binary Tree Level Order Traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal' },
  { id: 70, title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree' },
  { id: 71, title: 'Convert Sorted Array to Binary Search Tree', slug: 'convert-sorted-array-to-binary-search-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree' },
  { id: 72, title: 'Balanced Binary Tree', slug: 'balanced-binary-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/balanced-binary-tree' },
  { id: 73, title: 'Minimum Depth of Binary Tree', slug: 'minimum-depth-of-binary-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/minimum-depth-of-binary-tree' },
  { id: 74, title: 'Path Sum', slug: 'path-sum', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/path-sum' },
  { id: 75, title: 'Sum Root to Leaf Numbers', slug: 'sum-root-to-leaf-numbers', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/sum-root-to-leaf-numbers' },
  { id: 76, title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum' },
  { id: 77, title: 'Construct Binary Tree from Preorder and Inorder Traversal', slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal' },
  { id: 78, title: 'Validate Binary Search Tree', slug: 'validate-binary-search-tree', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree' },
  { id: 79, title: 'Kth Smallest Element in a BST', slug: 'kth-smallest-element-in-a-bst', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst' },
  { id: 80, title: 'Lowest Common Ancestor of a Binary Search Tree', slug: 'lowest-common-ancestor-of-a-binary-search-tree', difficulty: 'Easy', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree' },
  { id: 81, title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree' },
  { id: 82, title: 'Populating Next Right Pointers in Each Node', slug: 'populating-next-right-pointers-in-each-node', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node' },
  { id: 83, title: 'Lowest Common Ancestor of a Binary Tree', slug: 'lowest-common-ancestor-of-a-binary-tree', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree' },
  { id: 84, title: 'Binary Tree Right Side View', slug: 'binary-tree-right-side-view', difficulty: 'Medium', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-right-side-view' },
  { id: 85, title: 'Course Schedule', slug: 'course-schedule', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/course-schedule' },
  { id: 86, title: 'Course Schedule II', slug: 'course-schedule-ii', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii' },
  { id: 87, title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/number-of-islands' },
  { id: 88, title: 'Clone Graph', slug: 'clone-graph', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/clone-graph' },
  { id: 89, title: 'Graph Valid Tree', slug: 'graph-valid-tree', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/graph-valid-tree' },
  { id: 90, title: 'Number of Connected Components in an Undirected Graph', slug: 'number-of-connected-components-in-an-undirected-graph', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph' },
  { id: 91, title: 'Course Schedule III', slug: 'course-schedule-iii', difficulty: 'Hard', category: 'Greedy', leetcodeUrl: 'https://leetcode.com/problems/course-schedule-iii' },
  { id: 92, title: 'Reconstruct Itinerary', slug: 'reconstruct-itinerary', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/reconstruct-itinerary' },
  { id: 93, title: 'Minimum Height Trees', slug: 'minimum-height-trees', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/minimum-height-trees' },
  { id: 94, title: 'Minimum Spanning Tree (concept)', slug: 'minimum-spanning-tree', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problemset/all/' },
  { id: 95, title: 'Dijkstra / Shortest Path (concept)', slug: 'shortest-path', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problemset/all/' },
  { id: 96, title: 'Topological Sort (concept)', slug: 'topological-sort', difficulty: 'Medium', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problemset/all/' },
  { id: 97, title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs' },
  { id: 98, title: 'House Robber', slug: 'house-robber', difficulty: 'Easy', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/house-robber' },
  { id: 99, title: 'House Robber II', slug: 'house-robber-ii', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/house-robber-ii' },
  { id: 100, title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence' },
  { id: 101, title: 'Word Break', slug: 'word-break', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/word-break' },
  { id: 102, title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium', category: 'Dynamic Programming', leetcodeUrl: 'https://leetcode.com/problems/coin-change' },
  { id: 103, title: 'Combination Sum IV', slug: 'combination-sum-iv', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/combination-sum-iv' },
  { id: 104, title: 'Palindromic Substrings', slug: 'palindromic-substrings', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/palindromic-substrings' },
  { id: 105, title: 'Decode Ways', slug: 'decode-ways', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/decode-ways' },
  { id: 106, title: 'Unique Paths', slug: 'unique-paths', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/unique-paths' },
  { id: 107, title: 'Word Ladder', slug: 'word-ladder', difficulty: 'Hard', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/word-ladder' },
  { id: 108, title: 'Word Ladder II', slug: 'word-ladder-ii', difficulty: 'Hard', category: 'Graphs', leetcodeUrl: 'https://leetcode.com/problems/word-ladder-ii' },
  { id: 109, title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree' },
  { id: 110, title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard', category: 'Trees', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum' },
  { id: 111, title: 'Longest Consecutive Sequence', slug: 'longest-consecutive-sequence', difficulty: 'Hard', category: 'Union-Find', leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence' },
  { id: 112, title: 'Design Twitter', slug: 'design-twitter', difficulty: 'Medium', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/design-twitter' },
  { id: 113, title: 'LRU Cache', slug: 'lru-cache', difficulty: 'Medium', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/lru-cache' },
  { id: 114, title: 'Min Stack', slug: 'min-stack', difficulty: 'Easy', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/min-stack' },
  { id: 115, title: 'Implement Trie (Prefix Tree)', slug: 'implement-trie-prefix-tree', difficulty: 'Medium', category: 'Trie', leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree' },
  { id: 116, title: 'Add and Search Word - Data structure design', slug: 'add-and-search-word-data-structure-design', difficulty: 'Medium', category: 'Trie', leetcodeUrl: 'https://leetcode.com/problems/add-and-search-word-data-structure-design' },
  { id: 117, title: 'Word Search', slug: 'word-search', difficulty: 'Medium', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/word-search' },
  { id: 118, title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard', category: 'Backtracking', leetcodeUrl: 'https://leetcode.com/problems/word-search-ii' },
  { id: 119, title: 'Find Median from Data Stream', slug: 'find-median-from-data-stream', difficulty: 'Hard', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream' },
  { id: 120, title: 'Sliding Window Maximum', slug: 'sliding-window-maximum', difficulty: 'Hard', category: 'Deque', leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum' },
  { id: 121, title: 'Longest Increasing Path in a Matrix', slug: 'longest-increasing-path-in-a-matrix', difficulty: 'Hard', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix' },
  { id: 122, title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray' },
  { id: 123, title: 'Word Pattern', slug: 'word-pattern', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/word-pattern' },
  { id: 124, title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/valid-anagram' },
  { id: 125, title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/group-anagrams' },
  { id: 126, title: 'Top K Frequent Words', slug: 'top-k-frequent-words', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-words' },
  { id: 127, title: 'Implement Queue using Stacks', slug: 'implement-queue-using-stacks', difficulty: 'Easy', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/implement-queue-using-stacks' },
  { id: 128, title: 'Implement Stack using Queues', slug: 'implement-stack-using-queues', difficulty: 'Easy', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/implement-stack-using-queues' },
  { id: 129, title: 'Design Circular Queue', slug: 'design-circular-queue', difficulty: 'Medium', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/design-circular-queue' },
  { id: 130, title: 'Design Parking System', slug: 'design-parking-system', difficulty: 'Easy', category: 'Design', leetcodeUrl: 'https://leetcode.com/problems/design-parking-system' },
  { id: 131, title: 'Implement pow(x, n)', slug: 'powx-n', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/powx-n' },
  { id: 132, title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-and-sell-stock', difficulty: 'Easy', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock' },
  { id: 133, title: 'Best Time to Buy and Sell Stock II', slug: 'best-time-to-buy-and-sell-stock-ii', difficulty: 'Medium', category: 'Greedy', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii' },
  { id: 134, title: 'Best Time to Buy and Sell Stock III', slug: 'best-time-to-buy-and-sell-stock-iii', difficulty: 'Hard', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii' },
  { id: 135, title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Easy', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray' },
  { id: 136, title: 'Maximum Product Subarray (duplicate)', slug: 'maximum-product-subarray', difficulty: 'Medium', category: 'DP', leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray' },
  { id: 137, title: 'Contains Duplicate', slug: 'contains-duplicate', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate' },
  { id: 138, title: 'Contains Duplicate II', slug: 'contains-duplicate-ii', difficulty: 'Easy', category: 'Hash Table', leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate-ii' },
  { id: 139, title: 'Contains Duplicate III', slug: 'contains-duplicate-iii', difficulty: 'Medium', category: 'BST', leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate-iii' },
  { id: 140, title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium', category: 'Array', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self' },
  { id: 141, title: 'Find Minimum in Rotated Sorted Array', slug: 'find-minimum-in-rotated-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array' },
  { id: 142, title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array' },
  { id: 143, title: 'Find Peak Element', slug: 'find-peak-element', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/find-peak-element' },
  { id: 144, title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/binary-search' },
  { id: 145, title: 'Search a 2D Matrix II', slug: 'search-a-2d-matrix-ii', difficulty: 'Medium', category: 'Binary Search', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix-ii' },
  { id: 146, title: 'Find K Pairs with Smallest Sums', slug: 'find-k-pairs-with-smallest-sums', difficulty: 'Medium', category: 'Heap', leetcodeUrl: 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums' },
  { id: 147, title: 'Product of Two Numbers (concept)', slug: 'product-of-two-numbers', difficulty: 'Easy', category: 'Math', leetcodeUrl: 'https://leetcode.com/problemset/all/' },
  { id: 148, title: 'Add Strings', slug: 'add-strings', difficulty: 'Easy', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/add-strings' },
  { id: 149, title: 'Multiply Strings', slug: 'multiply-strings', difficulty: 'Medium', category: 'String', leetcodeUrl: 'https://leetcode.com/problems/multiply-strings' },
  { id: 150, title: 'Fraction to Recurring Decimal', slug: 'fraction-to-recurring-decimal', difficulty: 'Medium', category: 'Math', leetcodeUrl: 'https://leetcode.com/problems/fraction-to-recurring-decimal' },
]

export default NEETCODE150
