import {
  Schema,
  model,
  models,
  type HydratedDocument,
  type SchemaDefinition,
  type Types,
} from "mongoose";
import { createBaseSchemaOptions, optionalString, requiredString } from "./shared";

export interface ComparisonDeltas {
  totalSolved: number;
  easySolved: number;
  mediumSolved: number;
  hardSolved: number;
  streak: number;
}

export interface Comparison {
  userId: Types.ObjectId;
  baselineSnapshotId: Types.ObjectId;
  currentSnapshotId: Types.ObjectId;
  title: string;
  summary: string;
  deltas: ComparisonDeltas;
  notes?: string;
  generatedBy: string;
}

const comparisonSchemaDefinition: SchemaDefinition<Comparison> = {
  userId: {
    type: Schema.Types.ObjectId,
    ref: "User",
    required: [true, "User reference is required"],
    index: true,
  },
  baselineSnapshotId: {
    type: Schema.Types.ObjectId,
    ref: "Snapshot",
    required: [true, "Baseline snapshot reference is required"],
    index: true,
  },
  currentSnapshotId: {
    type: Schema.Types.ObjectId,
    ref: "Snapshot",
    required: [true, "Current snapshot reference is required"],
    index: true,
  },
  title: requiredString("Comparison title is required"),
  summary: requiredString("Comparison summary is required"),
  deltas: {
    totalSolved: {
      type: Number,
      default: 0,
    },
    easySolved: {
      type: Number,
      default: 0,
    },
    mediumSolved: {
      type: Number,
      default: 0,
    },
    hardSolved: {
      type: Number,
      default: 0,
    },
    streak: {
      type: Number,
      default: 0,
    },
  },
  notes: optionalString(),
  generatedBy: requiredString("Generated by is required", {
    default: "system",
  }),
};

const comparisonSchema = new Schema<Comparison>(comparisonSchemaDefinition, createBaseSchemaOptions());

comparisonSchema.index(
  { userId: 1, baselineSnapshotId: 1, currentSnapshotId: 1 },
  { unique: true },
);

export type ComparisonDocument = HydratedDocument<Comparison>;

export const ComparisonModel = models.Comparison ?? model<Comparison>("Comparison", comparisonSchema);
